(gtk_accel_path "<Actions>/terminal-window/move-tab-left" "<Primary><Shift>Left")
(gtk_accel_path "<Actions>/terminal-window/move-tab-right" "<Primary><Shift>Right")
(gtk_accel_path "<Actions>/terminal-window/next-tab" "<Shift>Right")
(gtk_accel_path "<Actions>/terminal-window/prev-tab" "<Shift>Left")
(gtk_accel_path "<Actions>/terminal-window/reset-and-clear" "<Primary><Shift>k")
